services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001/api}
        VITE_WS_URL: ${VITE_WS_URL:-http://localhost:3001}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      REDIS_HOST: redis          # 👈 Add this
      REDIS_PORT: 6379 
    depends_on:
      - redis
      
  simulator:
    build: ./simulator
    ports:
      - "8080:8080"
    depends_on:
      - redis
    